import { createFileRoute, Link } from "@tanstack/react-router";
import { PageHeader, Panel } from "@/components/app-shell";
import { EducationShell } from "@/components/education-shell";
import { Button } from "@/components/ui/button";
import data from "@/generated/compared-to-what-data.json";

/**
 * Slice 5 — the two questions that decide whether a backtest means anything.
 *
 * Every number here is generated by `scripts/precompute-compared-to-what.mjs`
 * straight out of the committed research output. Nothing is typed in by hand, so
 * this page cannot drift from the experiments it teaches from.
 *
 * The three exhibits are deliberately from three different strategy families —
 * a coin screen, a volume signal, a Fibonacci level — because the point is that
 * the mistake is not specific to any one method.
 */
export const Route = createFileRoute("/compared-to-what")({
  head: () => ({ meta: [{ title: "เทียบกับอะไร นับกี่ครั้ง · Walk-Forward Lab" }] }),
  component: ComparedToWhat,
});

const pct = (value: number, digits = 1) => `${(value * 100).toFixed(digits)}%`;
const signedPct = (value: number, digits = 2) =>
  `${value >= 0 ? "+" : ""}${(value * 100).toFixed(digits)}%`;
const tone = (value: number) => (value >= 0 ? "text-positive" : "text-destructive");

// Research ids are fine in the JSON; a student should read levels, not codes.
const ZONE_LABELS: Record<string, string> = {
  Z1_0382: "0.382",
  Z2_0500: "0.500",
  Z3_golden: "0.618–0.66 (golden pocket)",
  Z4_0786: "0.786",
  Z5_random: "ระดับสุ่ม",
};

function ComparedToWhat() {
  const { screen, counting, levels } = data;
  const ninety = screen.horizons.find((row) => row.days === 90) ?? screen.horizons[0];
  const twenty = counting.rows.find((row) => row.days === 20) ?? counting.rows[0];
  const claim = levels.zones.find((zone) => zone.isClaim);
  const control = levels.zones.find((zone) => zone.isControl);

  return (
    <EducationShell>
      <PageHeader
        kicker="EDUCATION · READ-ONLY RESEARCH · NO LIVE ORDER"
        title="เทียบกับอะไร และนับกี่ครั้ง"
        subtitle="สองคำถามที่ตัดสินว่า backtest มีความหมายไหม — ถามผิดไปข้อเดียว ตัวเลขที่ดูดีมากก็หายไปทั้งหมด สามตัวอย่างข้างล่างมาจากคนละตระกูลกลยุทธ์ เพื่อให้เห็นว่านี่ไม่ใช่ปัญหาของวิธีใดวิธีหนึ่ง"
      />

      <div className="space-y-6 p-6">
        <Panel title="สรุปก่อนดูตัวเลข" subtitle="ถ้าจำได้แค่สองบรรทัดจากหน้านี้ ให้จำสองบรรทัดนี้">
          <div className="grid gap-3 md:grid-cols-2">
            <div className="rounded-md border p-4">
              <div className="text-xs uppercase tracking-wide text-muted-foreground">
                คำถามที่ 1
              </div>
              <div className="mt-1 text-xl font-semibold">เทียบกับอะไร?</div>
              <p className="mt-2 text-sm text-muted-foreground">
                ตัวกรองที่ &quot;ได้ผลดี&quot; ต้องเทียบกับสิ่งที่มันคัดทิ้ง
                และเทียบกับการไม่กรองเลย ไม่งั้นคุณกำลังวัดว่าตลาดขึ้น ไม่ได้วัดว่าตัวกรองทำงาน
              </p>
            </div>
            <div className="rounded-md border p-4">
              <div className="text-xs uppercase tracking-wide text-muted-foreground">
                คำถามที่ 2
              </div>
              <div className="mt-1 text-xl font-semibold">นับกี่ครั้ง?</div>
              <p className="mt-2 text-sm text-muted-foreground">
                สัญญาณที่เกิดติด ๆ กันในรอบเดียว ไม่ใช่หลักฐานหลายชิ้น
                มันคือหลักฐานชิ้นเดียวที่ถูกนับซ้ำ — และการนับซ้ำทำให้ผลดูมีนัยสำคัญทั้งที่ไม่มี
              </p>
            </div>
          </div>
        </Panel>

        {/* ---------------- Exhibit A ---------------- */}
        <Panel
          title="ตัวอย่างที่ 1 — ตัวกรองเหรียญ: เทียบกับสิ่งที่มันคัดทิ้ง"
          subtitle="ตัวกรองถูกออกแบบให้เก็บเหรียญที่แนวโน้มเป็นบวก คำถามเดียวคือ เหรียญที่มันทิ้งไปเป็นยังไง"
        >
          <div className="overflow-x-auto">
            <table className="w-full min-w-[520px] text-sm">
              <thead className="text-xs text-muted-foreground">
                <tr className="border-b">
                  <th className="py-2 text-left font-medium">มองไปข้างหน้า</th>
                  <th className="py-2 text-right font-medium">เหรียญที่ตัวกรอง “เก็บ”</th>
                  <th className="py-2 text-right font-medium">เหรียญที่ตัวกรอง “ทิ้ง”</th>
                  <th className="py-2 text-right font-medium">ตัวกรองถูกไหม</th>
                </tr>
              </thead>
              <tbody>
                {screen.horizons.map((row) => (
                  <tr key={row.days} className="border-b last:border-0">
                    <td className="py-2">{row.days} วัน</td>
                    <td className={`py-2 text-right tabular-nums ${tone(row.keptMean)}`}>
                      {signedPct(row.keptMean, 1)}
                      <span className="ml-1 text-xs text-muted-foreground">
                        (n={row.nKept.toLocaleString()})
                      </span>
                    </td>
                    <td className={`py-2 text-right tabular-nums ${tone(row.droppedMean)}`}>
                      {signedPct(row.droppedMean, 1)}
                      <span className="ml-1 text-xs text-muted-foreground">
                        (n={row.nDropped.toLocaleString()})
                      </span>
                    </td>
                    <td className="py-2 text-right font-medium text-destructive">
                      {row.screenWasRight ? "ถูก" : "ผิด"}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-3 text-sm text-muted-foreground">
            เหรียญที่ถูกทิ้งให้ผลตอบแทน<strong className="text-foreground">ดีกว่า</strong>
            เหรียญที่ถูกเก็บ ทุกช่วงเวลา — ที่ {ninety.days} วันคือ{" "}
            {signedPct(ninety.droppedMean, 1)} เทียบกับ {signedPct(ninety.keptMean, 1)}{" "}
            ถ้าดูแค่ผลของพอร์ตที่กรองแล้วในตลาดกระทิง มันจะดูเหมือนตัวกรองทำงาน
            สิ่งที่เปิดโปงมันคือการเทียบกับกองที่ถูกทิ้ง
          </p>
        </Panel>

        {/* ---------------- Exhibit B ---------------- */}
        <Panel
          title="ตัวอย่างที่ 2 — สัญญาณวอลุ่ม: ข้อมูลชุดเดิม เปลี่ยนแค่วิธีนับ"
          subtitle={`สัญญาณเดิม ข้อมูลเดิม ไม่มีการปรับพารามิเตอร์ใด ๆ — เปลี่ยนแค่ว่า ${counting.rawSignals} สัญญาณที่เกาะกลุ่มกันนับเป็น ${counting.episodes} เหตุการณ์`}
        >
          <div className="overflow-x-auto">
            <table className="w-full min-w-[560px] text-sm">
              <thead className="text-xs text-muted-foreground">
                <tr className="border-b">
                  <th className="py-2 text-left font-medium">มองไปข้างหน้า</th>
                  <th className="py-2 text-right font-medium">นับซ้ำ (n={counting.rawSignals})</th>
                  <th className="py-2 text-right font-medium">
                    นับ 1 รอบ = 1 (n={counting.episodes})
                  </th>
                  <th className="py-2 text-right font-medium">ค่าฐาน</th>
                </tr>
              </thead>
              <tbody>
                {counting.rows.map((row) => (
                  <tr key={row.days} className="border-b last:border-0">
                    <td className="py-2">{row.days} วัน</td>
                    <td className="py-2 text-right tabular-nums">
                      <span className={tone(row.clusteredMean)}>
                        {signedPct(row.clusteredMean)}
                      </span>
                      <span className="ml-2 rounded bg-muted px-1.5 py-0.5 text-xs text-muted-foreground">
                        {pct(row.clusteredPercentile)}
                      </span>
                    </td>
                    <td className="py-2 text-right tabular-nums">
                      <span className={tone(row.episodeMean)}>{signedPct(row.episodeMean)}</span>
                      <span className="ml-2 rounded bg-muted px-1.5 py-0.5 text-xs text-muted-foreground">
                        {pct(row.episodePercentile)}
                      </span>
                    </td>
                    <td className="py-2 text-right tabular-nums text-muted-foreground">
                      {signedPct(row.baseMean)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-3 text-sm text-muted-foreground">
            ตัวเลขในกล่องเทาคือ &quot;ชนะการสุ่มกี่เปอร์เซ็นต์&quot; — 50% แปลว่าเหมือนสุ่มวันมั่ว ๆ
            ที่ {twenty.days} วัน การนับซ้ำให้ {pct(twenty.clusteredPercentile)}{" "}
            ซึ่งดูเหมือนของจริงมาก พอนับ 1 รอบเป็น 1 เหลือ {pct(twenty.episodePercentile)}{" "}
            และผลตอบแทน <strong className="text-foreground">ต่ำกว่าค่าฐาน</strong> (
            {signedPct(twenty.episodeMean)} เทียบกับ {signedPct(twenty.baseMean)})
            อัตราชนะก็ต่ำกว่าค่าฐาน ({pct(twenty.episodeWinRate)} เทียบกับ {pct(twenty.baseWinRate)}
            )
          </p>
        </Panel>

        {/* ---------------- Exhibit C ---------------- */}
        <Panel
          title="ตัวอย่างที่ 3 — ระดับ Fibonacci: ต้องใช้ทั้งสองคำถามพร้อมกัน"
          subtitle={`ทุกโซนกว้างเท่ากัน วัดที่ swing lookback ${levels.lookback} มองไปข้างหน้า ${levels.horizon} แท่ง และมี “ระดับสุ่ม” เป็นตัวเทียบ`}
        >
          <div className="overflow-x-auto">
            <table className="w-full min-w-[480px] text-sm">
              <thead className="text-xs text-muted-foreground">
                <tr className="border-b">
                  <th className="py-2 text-left font-medium">โซน</th>
                  <th className="py-2 text-right font-medium">n</th>
                  <th className="py-2 text-right font-medium">ผลตอบแทนเฉลี่ย</th>
                  <th className="py-2 text-right font-medium">ชนะการสุ่ม</th>
                </tr>
              </thead>
              <tbody>
                {levels.zones.map((zone) => (
                  <tr
                    key={zone.id}
                    className={`border-b last:border-0 ${zone.isClaim || zone.isControl ? "font-medium" : ""}`}
                  >
                    <td className="py-2">
                      {ZONE_LABELS[zone.id] ?? zone.id}
                      {zone.isClaim ? (
                        <span className="ml-2 rounded bg-primary/10 px-1.5 py-0.5 text-xs text-primary">
                          ข้อกล่าวอ้าง
                        </span>
                      ) : null}
                      {zone.isControl ? (
                        <span className="ml-2 rounded bg-muted px-1.5 py-0.5 text-xs text-muted-foreground">
                          ตัวเทียบสุ่ม
                        </span>
                      ) : null}
                    </td>
                    <td className="py-2 text-right tabular-nums text-muted-foreground">{zone.n}</td>
                    <td className={`py-2 text-right tabular-nums ${tone(zone.mean)}`}>
                      {signedPct(zone.mean)}
                    </td>
                    <td className="py-2 text-right tabular-nums text-muted-foreground">
                      {pct(zone.percentile)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="mt-4 grid gap-3 md:grid-cols-3">
            <div className="rounded-md border p-4">
              <div className="text-xs text-muted-foreground">วัดทั้งหมด</div>
              <div className="mt-1 text-3xl font-semibold">{levels.measurements}</div>
              <div className="mt-1 text-xs text-muted-foreground">
                ข้ามเกณฑ์นัยสำคัญ {levels.crossedThreshold} ข้อ (ช่วง {pct(levels.minPercentile)}–
                {pct(levels.maxPercentile)})
              </div>
            </div>
            <div className="rounded-md border p-4">
              <div className="text-xs text-muted-foreground">ส่วนต่างระหว่างระดับ fib ทั้ง 4</div>
              <div className="mt-1 text-3xl font-semibold">
                {(levels.fibSpread * 100).toFixed(2)}
              </div>
              <div className="mt-1 text-xs text-muted-foreground">จุดเปอร์เซ็นต์</div>
            </div>
            <div className="rounded-md border p-4">
              <div className="text-xs text-muted-foreground">
                ส่วนต่างของ “ระดับสุ่ม” ระดับเดียว เมื่อเปลี่ยนแค่วิธีนับ swing
              </div>
              <div className="mt-1 text-3xl font-semibold">
                {(levels.parameterNoise * 100).toFixed(2)}
              </div>
              <div className="mt-1 text-xs text-muted-foreground">จุดเปอร์เซ็นต์</div>
            </div>
          </div>

          <p className="mt-3 text-sm text-muted-foreground">
            {claim && control ? (
              <>
                ที่การตั้งค่าหลัก โซน golden pocket ได้ {signedPct(claim.mean)} ขณะที่{" "}
                <strong className="text-foreground">ระดับสุ่มได้ {signedPct(control.mean)}</strong>{" "}
                — ตัวที่ทำผลดีที่สุดคือตัวเทียบสุ่ม{" "}
              </>
            ) : null}
            และตัวเลขสองกล่องขวาคือหัวใจ: การเถียงว่า 0.618 ดีกว่า 0.5 ไหม มีขนาดพอ ๆ
            กับการเถียงว่าจะนับ swing ยังไง ซึ่งเป็นสิ่งที่คนลากเส้นเลือกเองด้วยมือ
          </p>
        </Panel>

        <Panel
          title="เอาไปใช้ยังไง"
          subtitle="เช็คลิสต์ 4 ข้อ ก่อนเชื่อ backtest ของใครก็ตาม รวมถึงของตัวเอง"
        >
          <ol className="list-decimal space-y-2 pl-5 text-sm text-muted-foreground">
            <li>
              <strong className="text-foreground">ตัวเทียบคืออะไร</strong> — ถ้าไม่มีการเทียบกับ
              &quot;ไม่ทำอะไรเลย&quot; หรือ &quot;สุ่ม&quot; ตัวเลขนั้นยังไม่บอกอะไร
            </li>
            <li>
              <strong className="text-foreground">นับกี่ครั้งจริง ๆ</strong> —
              สัญญาณที่เกิดติดกันในรอบเดียว ควรนับเป็นหนึ่ง
            </li>
            <li>
              <strong className="text-foreground">ลองกี่แบบกว่าจะเจอแบบนี้</strong> — ถ้าทดสอบ 45
              แบบ ควรมีบางแบบดูดีโดยบังเอิญเสมอ
            </li>
            <li>
              <strong className="text-foreground">
                ผลเปลี่ยนไหมถ้าขยับพารามิเตอร์ที่เราเลือกเอง
              </strong>{" "}
              — ถ้าเปลี่ยนมากกว่าตัวเอฟเฟกต์เอง แปลว่ากำลังวัด noise
            </li>
          </ol>
          <div className="mt-4 flex flex-wrap gap-2">
            <Button asChild variant="outline" size="sm">
              <Link to="/walk-forward-overfit">ดูบทเรียน overfitting ต่อ</Link>
            </Button>
            <Button asChild variant="outline" size="sm">
              <Link to="/walk-forward" search={{ variant: "baseline", cost: "thai" }}>
                กลับไปดูผลราย fold
              </Link>
            </Button>
          </div>
          <p className="mt-4 text-xs text-muted-foreground">
            ตัวเลขทุกตัวในหน้านี้ถูกดึงมาจากผลการทดลองที่บันทึกไว้ ({data.source.screen},{" "}
            {data.source.counting}, {data.source.levels}) ตอน build —
            ไม่มีการพิมพ์ตัวเลขลงหน้าเว็บด้วยมือ หน้านี้จึงเพี้ยนไปจากงานวิจัยไม่ได้
          </p>
        </Panel>
      </div>
    </EducationShell>
  );
}
