import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { AppShell, PageHeader, Panel } from "@/components/app-shell";
import { REPORTS_DATA } from "@/lib/demo-data";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { FileText, Download, Eye, ShieldCheck } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/reports")({
  head: () => ({ meta: [{ title: "Reports · Aegis Fund OS" }] }),
  component: ReportsPage,
});

function statusColor(s: string) {
  if (s === "Locked" || s === "Final") return "border-positive/40 text-positive bg-positive/5";
  if (s === "Reviewed") return "border-info/40 text-info bg-info/5";
  return "border-warning/40 text-warning bg-warning/5";
}

function ReportsPage() {
  const [preview, setPreview] = useState<(typeof REPORTS_DATA)[number] | null>(null);
  return (
    <AppShell>
      <PageHeader
        kicker="Investor-grade outputs"
        title="Reports"
        subtitle="Every artifact is versioned, hashed, and traceable to its source ledger and reconciliation state."
        actions={<Button size="sm"><FileText className="h-3.5 w-3.5" /> New report</Button>}
      />
      <div className="p-6 space-y-6">
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {REPORTS_DATA.map((r) => (
            <div key={r.name} className="rounded-md border border-border/70 bg-card/50 p-4 flex flex-col gap-3">
              <div className="flex items-start justify-between gap-2">
                <div className="min-w-0">
                  <div className="text-sm font-semibold leading-tight">{r.name}</div>
                  <div className="text-[11px] text-muted-foreground mt-0.5 num">Period {r.period} · {r.version}</div>
                </div>
                <span className={`shrink-0 rounded border px-2 py-0.5 text-[10px] uppercase tracking-wider ${statusColor(r.status)}`}>{r.status}</span>
              </div>
              <dl className="grid grid-cols-2 gap-y-1 text-[11px]">
                <dt className="text-muted-foreground">Generated by</dt><dd className="text-right">{r.by}</dd>
                <dt className="text-muted-foreground">Reviewed by</dt><dd className="text-right">{r.reviewed}</dd>
                <dt className="text-muted-foreground">Checksum</dt><dd className="text-right font-mono">{r.checksum}</dd>
              </dl>
              <div className="mt-auto flex gap-2">
                <Button size="sm" variant="outline" className="flex-1" onClick={() => setPreview(r)}><Eye className="h-3.5 w-3.5" /> Preview</Button>
                <Button size="sm" variant="ghost" onClick={() => toast.success(`${r.name} export queued (demo)`)}><Download className="h-3.5 w-3.5" /></Button>
              </div>
            </div>
          ))}
        </div>

        <Panel title="Distribution log" subtitle="Recent deliveries — demo">
          <ol className="space-y-2 text-sm">
            {[
              ["2025-11-10 09:12", "Exposure Report — 2025-11-10", "GP LP portal", "Sent"],
              ["2025-11-04 17:44", "Monthly Factsheet — Oct 2025", "Investor group A", "Sent"],
              ["2025-10-31 21:03", "Audit Evidence Pack — Q3 2025", "Auditor (Read-only)", "Sealed"],
            ].map((r, i) => (
              <li key={i} className="flex items-center gap-3 border-b border-border/40 pb-2 last:border-0">
                <span className="text-[11px] text-muted-foreground num w-32">{r[0]}</span>
                <span className="text-sm flex-1">{r[1]}</span>
                <span className="text-xs text-muted-foreground">{r[2]}</span>
                <Badge variant="outline" className="text-[10px]">{r[3]}</Badge>
              </li>
            ))}
          </ol>
        </Panel>
      </div>

      <Dialog open={!!preview} onOpenChange={(o) => !o && setPreview(null)}>
        <DialogContent className="max-w-2xl">
          {preview && (
            <>
              <DialogHeader>
                <DialogTitle>{preview.name}</DialogTitle>
                <DialogDescription>Preview · {preview.version} · {preview.status}</DialogDescription>
              </DialogHeader>
              <div className="rounded-md border border-border/60 bg-panel text-panel-foreground p-6 max-h-[60vh] overflow-y-auto">
                <div className="text-[10px] uppercase tracking-[0.2em] text-panel-foreground/60">Aegis Global Opportunities Fund I</div>
                <h2 className="display text-2xl font-semibold mt-1">{preview.name}</h2>
                <p className="text-sm text-panel-foreground/70 mt-1">Period: {preview.period}</p>
                <hr className="my-4 border-panel-foreground/15" />
                <div className="grid grid-cols-3 gap-3 tabular">
                  <div><div className="text-[10px] uppercase text-panel-foreground/60">NAV</div><div className="num font-semibold">$128,734,512.44</div></div>
                  <div><div className="text-[10px] uppercase text-panel-foreground/60">YTD Return</div><div className="num font-semibold text-positive">+11.47%</div></div>
                  <div><div className="text-[10px] uppercase text-panel-foreground/60">Max DD</div><div className="num font-semibold">-6.84%</div></div>
                </div>
                <p className="text-sm text-panel-foreground/80 leading-relaxed mt-4">
                  This is a demo preview of an investor-grade artifact. In production the layout is generated
                  server-side into a signed PDF containing performance attribution, exposure, risk statistics,
                  reconciliation summary, and provenance metadata. Outputs are watermarked <em>DEMO</em>.
                </p>
                <div className="mt-4 text-[11px] text-panel-foreground/60">
                  Checksum <span className="font-mono">{preview.checksum}</span> · Reviewed by {preview.reviewed}
                </div>
              </div>
              <DialogFooter>
                <div className="mr-auto flex items-center gap-2 text-[11px] text-muted-foreground"><ShieldCheck className="h-3.5 w-3.5 text-positive" /> Watermarked as demo</div>
                <Button variant="ghost" onClick={() => setPreview(null)}>Close</Button>
                <Button onClick={() => { toast.success("Export queued (demo)"); setPreview(null); }}>Export PDF</Button>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>
    </AppShell>
  );
}

