/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AotPaperGridRouteImport } from './routes/aot-paper-grid'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotsNewRouteImport } from './routes/bots_.new'
import { Route as BotsBotIdRouteImport } from './routes/bots_.$botId'
import { Route as BotsBotIdProfitRouteImport } from './routes/bots_.$botId_.profit'
import { Route as BotsBotIdOrdersRouteImport } from './routes/bots_.$botId_.orders'
import { Route as BotsBotIdEventsRouteImport } from './routes/bots_.$botId_.events'

const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AotPaperGridRoute = AotPaperGridRouteImport.update({
  id: '/aot-paper-grid',
  path: '/aot-paper-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsNewRoute = BotsNewRouteImport.update({
  id: '/bots_/new',
  path: '/bots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/bots_/$botId',
  path: '/bots/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdProfitRoute = BotsBotIdProfitRouteImport.update({
  id: '/bots_/$botId_/profit',
  path: '/bots/$botId/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdOrdersRoute = BotsBotIdOrdersRouteImport.update({
  id: '/bots_/$botId_/orders',
  path: '/bots/$botId/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdEventsRoute = BotsBotIdEventsRouteImport.update({
  id: '/bots_/$botId_/events',
  path: '/bots/$botId/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/aot-paper-grid': typeof AotPaperGridRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bots': typeof BotsRoute
  '/integrations': typeof IntegrationsRoute
  '/ledger': typeof LedgerRoute
  '/portfolio': typeof PortfolioRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/bots/$botId/events': typeof BotsBotIdEventsRoute
  '/bots/$botId/orders': typeof BotsBotIdOrdersRoute
  '/bots/$botId/profit': typeof BotsBotIdProfitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/aot-paper-grid': typeof AotPaperGridRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bots': typeof BotsRoute
  '/integrations': typeof IntegrationsRoute
  '/ledger': typeof LedgerRoute
  '/portfolio': typeof PortfolioRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/bots/$botId/events': typeof BotsBotIdEventsRoute
  '/bots/$botId/orders': typeof BotsBotIdOrdersRoute
  '/bots/$botId/profit': typeof BotsBotIdProfitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/aot-paper-grid': typeof AotPaperGridRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/bots': typeof BotsRoute
  '/integrations': typeof IntegrationsRoute
  '/ledger': typeof LedgerRoute
  '/portfolio': typeof PortfolioRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/bots_/$botId': typeof BotsBotIdRoute
  '/bots_/new': typeof BotsNewRoute
  '/bots_/$botId_/events': typeof BotsBotIdEventsRoute
  '/bots_/$botId_/orders': typeof BotsBotIdOrdersRoute
  '/bots_/$botId_/profit': typeof BotsBotIdProfitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/accounts'
    | '/aot-paper-grid'
    | '/approvals'
    | '/audit'
    | '/bots'
    | '/integrations'
    | '/ledger'
    | '/portfolio'
    | '/reconciliation'
    | '/reports'
    | '/risk'
    | '/settings'
    | '/signals'
    | '/bots/$botId'
    | '/bots/new'
    | '/bots/$botId/events'
    | '/bots/$botId/orders'
    | '/bots/$botId/profit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/accounts'
    | '/aot-paper-grid'
    | '/approvals'
    | '/audit'
    | '/bots'
    | '/integrations'
    | '/ledger'
    | '/portfolio'
    | '/reconciliation'
    | '/reports'
    | '/risk'
    | '/settings'
    | '/signals'
    | '/bots/$botId'
    | '/bots/new'
    | '/bots/$botId/events'
    | '/bots/$botId/orders'
    | '/bots/$botId/profit'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/accounts'
    | '/aot-paper-grid'
    | '/approvals'
    | '/audit'
    | '/bots'
    | '/integrations'
    | '/ledger'
    | '/portfolio'
    | '/reconciliation'
    | '/reports'
    | '/risk'
    | '/settings'
    | '/signals'
    | '/bots_/$botId'
    | '/bots_/new'
    | '/bots_/$botId_/events'
    | '/bots_/$botId_/orders'
    | '/bots_/$botId_/profit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AccountsRoute: typeof AccountsRoute
  AotPaperGridRoute: typeof AotPaperGridRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  BotsRoute: typeof BotsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LedgerRoute: typeof LedgerRoute
  PortfolioRoute: typeof PortfolioRoute
  ReconciliationRoute: typeof ReconciliationRoute
  ReportsRoute: typeof ReportsRoute
  RiskRoute: typeof RiskRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
  BotsBotIdRoute: typeof BotsBotIdRoute
  BotsNewRoute: typeof BotsNewRoute
  BotsBotIdEventsRoute: typeof BotsBotIdEventsRoute
  BotsBotIdOrdersRoute: typeof BotsBotIdOrdersRoute
  BotsBotIdProfitRoute: typeof BotsBotIdProfitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aot-paper-grid': {
      id: '/aot-paper-grid'
      path: '/aot-paper-grid'
      fullPath: '/aot-paper-grid'
      preLoaderRoute: typeof AotPaperGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots_/new': {
      id: '/bots_/new'
      path: '/bots/new'
      fullPath: '/bots/new'
      preLoaderRoute: typeof BotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots_/$botId': {
      id: '/bots_/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots_/$botId_/profit': {
      id: '/bots_/$botId_/profit'
      path: '/bots/$botId/profit'
      fullPath: '/bots/$botId/profit'
      preLoaderRoute: typeof BotsBotIdProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots_/$botId_/orders': {
      id: '/bots_/$botId_/orders'
      path: '/bots/$botId/orders'
      fullPath: '/bots/$botId/orders'
      preLoaderRoute: typeof BotsBotIdOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots_/$botId_/events': {
      id: '/bots_/$botId_/events'
      path: '/bots/$botId/events'
      fullPath: '/bots/$botId/events'
      preLoaderRoute: typeof BotsBotIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AccountsRoute: AccountsRoute,
  AotPaperGridRoute: AotPaperGridRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  BotsRoute: BotsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LedgerRoute: LedgerRoute,
  PortfolioRoute: PortfolioRoute,
  ReconciliationRoute: ReconciliationRoute,
  ReportsRoute: ReportsRoute,
  RiskRoute: RiskRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
  BotsBotIdRoute: BotsBotIdRoute,
  BotsNewRoute: BotsNewRoute,
  BotsBotIdEventsRoute: BotsBotIdEventsRoute,
  BotsBotIdOrdersRoute: BotsBotIdOrdersRoute,
  BotsBotIdProfitRoute: BotsBotIdProfitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
